
#!/bin/bash

#System Information
DATE=$(date +%F)
TIME=$(date +%T)
host_name=$(hostname)
os_info=$(grep '^PRETTY_NAME=' /etc/os-release | cut -d= -f2- | tr -d '"')
uptime_info=$(uptime -p 2>/dev/null || who -b)

#Hardware Information
cpu_info=$(lscpu | grep "Model name" | awk -F ':' '{print $2}' | tr -d '[:space:]')
cpu_speed=$(lshw -c processor | awk -F ': ' '/capacity/ {gsub(/[[:space:]]/, "", $2); print $2; exit}')
ram=$(free -h | awk '/^Mem:/ {print $2}')
disks=$(lsblk -o NAME,MODEL,SIZE --noheadings)
video_card=$(lspci -nn | grep -i VGA | sed 's/.*: //')

#Network Information
fqdn=$(hostname).$(dnsdomainname)
host_address=$(ip -4 addr show scope global | grep -oP 'inet \K[\d.]+')
gateway=$(ip route | grep -oP 'default via \K\S+')
dns_server=$(grep -oP 'nameserver\s+\K\S+' /etc/resolv.conf)

#InterfaceName
ip_info=$(ip -o -4 addr show)
interface_name=$(echo "$ip_info" | grep -oP '^\d+: \K\w+')
ip_cidr=$(echo "$ip_info" | grep -oP '\d+\.\d+\.\d+\.\d+/\d+')

#System Status
USERS=$(who | awk '{print $1}' | sort -u | paste -sd ', ')
DISK_SPACE=$(df -h --output=target,avail | grep -v '^Filesystem' | awk '{print $1, $2}')
PROCESS_COUNT=$(ps --no-headers aux | wc -l)
IFS=' ' read -r LOAD1 LOAD5 LOAD15 _ < /proc/loadavg
LOAD_AVERAGES="$LOAD1 $LOAD5 $LOAD15"
MEMORY_ALLOCATION=$(free -h | awk '/^Mem:/ {print $2}')
LISTENING_PORTS=$(ss -tuln | awk 'NR > 1 && $5 ~ /:/ {split($5, a, ":"); print a[2]}' | sort -u | paste -sd ',')
UFW_RULES=$(sudo ufw status numbered | awk '{sub(/^[0-9]+ /, ""); print $2}')

echo "
System Report generated by $USERNAME, $DATE/$TIME
 
System Information
------------------
Hostname: $host_name
OS: $os_info
Uptime: $uptime_info
 
Hardware Information
--------------------
cpu: $cpu_info
Speed: $cpu_speed
Ram: $ram
Disk(s): 
$disks

Video: $video_card
 
Network Information
-------------------
FQDN: $fqdn
Host Address: $host_address
Gateway IP: $gateway
DNS Server: $dns_server
 
InterfaceName: $interface_name
IP Address: $ip_cidr
 
System Status
-------------
Users Logged In: $USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES
"
